hard_stops:
  - id: new_device_high_amount
    if: "not features.device_seen_before and features.amount_inr >= 75000"
    action: "HOLD"

soft_signals:
  - id: night_owl
    weight: 0.25
    if: "features.hour in [0,1,2,3,4]"
  - id: 10x_user_median
    weight: 0.45
    if: "features.user_median > 0 and features.amount_inr >= 10 * features.user_median"
  - id: peer_z_gt_3
    weight: 0.35
    if: "features.peer_z >= 3"

thresholds:
  allow_below: 0.35
  stepup_between: [0.35, 0.7]
  block_above: 0.7
